import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-[300px,1fr] h-screen">
          <div className="bg-sky-950/50 p-4 space-y-4">
            <Link
              className="block p-2 rounded bg-cyan-950"
              href="/parent-page-one">
              Parent Page One
            </Link>
            <Link
              className="block p-2 rounded bg-cyan-950"
              href="/parent-page-two">
              Parent Page Two
            </Link>
            <Link
              className="block p-2 rounded bg-cyan-950"
              href="/parent-page-three">
              Parent Page Three
            </Link>
            <Link
              className="block p-2 rounded bg-cyan-950"
              href="/parent-page-four">
              Parent Page Four
            </Link>
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
